declare module "@content/list/hsk1.json";
declare module "@content/list/hsk2.json";
declare module "@content/list/hsk3.json";
declare module "@content/list/hsk4.json";
declare module "@content/list/hsk5.json";
declare module "@content/list/hsk6.json";
declare module "@content/list/hsk7-9.json";
declare module "@content/list/allchar.json";
declare module "@content/list/chengyu.json";