declare module "src/contentlist/hsk1.json";
declare module "src/contentlist/hsk2.json";
declare module "src/contentlist/hsk3.json";
declare module "src/contentlist/hsk4.json";
declare module "src/contentlist/hsk5.json";
declare module "src/contentlist/hsk6.json";
declare module "src/contentlist/hsk7-9.json";
declare module "src/contentlist/allchar.json";
declare module "src/contentlist/chengyu.json";